services:
  - type: web
    name: shecares-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
